name: Sample
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo $TAURI_KEY_PASSWORD | sed 's/./& /g'
        env: 
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
